databases:
  - name: test-platform-db
    plan: free

services:
  - type: web
    name: test-platform
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: test-platform-db
          property: connectionString
