services:
  - type: web
    name: test-platform
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: DB_PATH
        value: /var/data/exam.db
    disks:
      - name: test-platform-data
        mountPath: /var/data
        sizeGB: 1
